site: b2c-crm-sync: A contemporary perspective on integrating B2C Commerce and the Salesforce Platform

url: https://sfb2csolutionarchitects.github.io
baseurl: https://sfb2csolutionarchitects.github.io/b2c-crm-sync/

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page:num/"
